---
abstract: 'Data objects for 9 protocol.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-9P
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mo: 0
  Mo::utils: 0.08
  Mo::utils::Array: 0
  Mo::utils::Binary: 0
  Mo::utils::Number::Alias: 0.09
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Data-9P/issues
  homepage: https://github.com/michal-josef-spacek/Data-9P
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Data-9P
version: '0.01'
